spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/demo_ds
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://localhost:3306/demo_ds
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://localhost:3306/demo_ds
      username: root   # 只读账户
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver